version: "3.8"

networks:
  md-hygiene-network:

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27019:27017"
    networks:
      - md-hygiene-network
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://admin:adminpassword@mongo:27017/admin", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: ./backend-MD-Hygiene  
      dockerfile: Dockerfile
    container_name: md-hygiene_backend
    ports:
      - "5010:5010"
    networks:
      - md-hygiene-network
    env_file:
      - ./backend-MD-Hygiene/.env
      - ./backend-MD-Hygiene/.env.${NODE_ENV:-development}  
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    entrypoint: ["sh", "-c", "sleep 5 && node server.js"]

  frontend:
    build:
      context: ./frontend-MD-Hygiene  
      dockerfile: Dockerfile
    container_name: md-hygiene_frontend
    ports:
      - "${VITE_PORT:-3003}:3003"
    networks:
      - md-hygiene-network
    env_file:
      - ./frontend-MD-Hygiene/.env
      - ./frontend-MD-Hygiene/.env.${NODE_ENV:-development}  
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_PORT=${VITE_PORT:-3003}
    depends_on:
      - backend
    restart: always
    command: ["sh", "-c", "npm run build && npx serve -s dist -l ${VITE_PORT:-3003}"]

volumes:
  mongo_data:
