version: "3.8"

networks:
  md-hygiene-network:

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27019:27017"  # Local için 27018'e yönlendirildi
    networks:
      - md-hygiene-network
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://admin:adminpassword@mongo:27017/admin", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: ./backend-MD-Hygiene  
      dockerfile: Dockerfile
    container_name: md-hygiene_backend
    ports:
      - "5010:5010"
    networks:
      - md-hygiene-network
    env_file:
      - ./backend-MD-Hygiene/.env
    environment:
      - NODE_ENV=${NODE_ENV:-development} 
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/md-hygiene}
      - SMTP_USER=${SMTP_USER:-info@md-hygienelogistik.de}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-AaBb1234,}
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    entrypoint: ["sh", "-c", "sleep 5 && node server.js"]

  frontend:
    build:
      context: ./frontend-MD-Hygiene  
      dockerfile: Dockerfile
    container_name: md-hygiene_frontend
    ports:
      - "3000:3000"  # Dışarıdan 3000'e yönlendirme
    networks:
      - md-hygiene-network
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:5010
    depends_on:
    - backend
    restart: always


volumes:
  mongo_data:
