version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://admin:adminpassword@mongo:27017/admin", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: ./backend-MD-Hygiene  
      dockerfile: Dockerfile
    container_name: md-hygiene_backend
    ports:
      - "5006:5006"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://admin:adminpassword@mongo:27017/md-hygiene
    env_file:
      - ./backend-MD-Hygiene/.env
    depends_on:
      mongo:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend-MD-Hygiene  
      dockerfile: Dockerfile
    container_name: md-hygiene_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:5006
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data:
